os:
  editPreset: 'nvim'
customCommands:
  - key: "<c-c>"
    context: "files"
    prompts:
      - type: "input"
        title: "Commit Message with Branch Name"
        key: "Message"
    command: git commit -m "[$(git branch --show-current)]:{{.Form.Message}}"
    description: "Custom commit message"
    output: terminal
gui:
  theme:
    activeBorderColor:
      - '#b4befe'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#b4befe'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

  authorColors:
    '*': '#b4befe'
