[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
poll-interval = 5

; Discharge config
label-discharging = %percentage% %
format-discharging = <ramp-capacity> <label-discharging>
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; Charging config
label-charging = %percentage% %
format-charging = <animation-charging> <label-charging>

animation-charging-0 =  
animation-charging-1 =  ﯓ
animation-charging-2 =  
animation-charging-3 =  ﯓ
animation-charging-4 =  
;; Framerate in milliseconds
animation-charging-framerate = 750

label-full =  %percentage%

