" Colorscheme generated by https://github.com/arcticlimer/djanho
highlight clear

function s:highlight(group, bg, fg, style)
  let gui = a:style == '' ? '' : 'gui=' . a:style
  let fg = a:fg == '' ? '' : 'guifg=' . a:fg
  let bg = a:bg == '' ? '' : 'guibg=' . a:bg
  exec 'hi ' . a:group . ' ' . bg . ' ' . fg  . ' ' . gui
endfunction

let s:Color4 = '#adbac7'
let s:Color7 = '#264365'
let s:Color1 = '#D699B6'
let s:Color3 = '#768390'
let s:Color2 = '#22272e'
let s:Color8 = '#1c2128'
let s:Color0 = '#E69875'
let s:Color5 = '#273732'
let s:Color6 = '#3f2d32'

call s:highlight('Operator', '', s:Color0, '')
call s:highlight('Number', '', s:Color1, '')
call s:highlight('StatusLine', s:Color3, s:Color2, '')
call s:highlight('WildMenu', s:Color2, s:Color4, '')
call s:highlight('Pmenu', s:Color2, s:Color4, '')
call s:highlight('PmenuSel', s:Color4, s:Color2, '')
call s:highlight('PmenuThumb', s:Color2, s:Color4, '')
call s:highlight('DiffAdd', s:Color5, '', '')
call s:highlight('DiffDelete', s:Color6, '', '')
call s:highlight('Normal', s:Color2, s:Color4, '')
call s:highlight('Visual', s:Color7, '', '')
call s:highlight('CursorLine', s:Color7, '', '')
call s:highlight('ColorColumn', s:Color7, '', '')
call s:highlight('SignColumn', s:Color2, '', '')
call s:highlight('LineNr', '', s:Color3, '')
call s:highlight('TabLine', s:Color8, s:Color3, '')
call s:highlight('TabLineSel', s:Color4, s:Color2, '')
call s:highlight('TabLineFill', s:Color8, s:Color3, '')
call s:highlight('TSPunctDelimiter', '', s:Color4, '')

highlight! link TSPunctBracket MyTag
highlight! link TSConstBuiltin TSVariableBuiltin
highlight! link CursorLineNr Identifier
highlight! link TSFunction Function
highlight! link TelescopeNormal Normal
highlight! link Macro Function
highlight! link TSTag MyTag
highlight! link Operator Keyword
highlight! link TSFuncMacro Macro
highlight! link TSParameter Constant
highlight! link NonText Comment
highlight! link Whitespace Comment
highlight! link TSNumber Number
highlight! link Conditional Operator
highlight! link Repeat Conditional
highlight! link TSNamespace TSType
highlight! link TSString String
highlight! link TSProperty TSField
highlight! link TSTagDelimiter Type
highlight! link TSLabel Type
highlight! link TSComment Comment
highlight! link Folded Comment
highlight! link TSField Constant
highlight! link TSRepeat Repeat
highlight! link TSPunctSpecial TSPunctDelimiter
highlight! link TSConstant Constant
highlight! link TSFloat Number
highlight! link TSType Type
highlight! link TSOperator Operator
highlight! link TSKeyword Keyword
highlight! link TSConditional Conditional
highlight! link TSParameterReference TSParameter
